### ISSUE TITLE
fix tauri changes

### ISSUE THREAD

**Issue by zenitogr** [HuakunShen/tauri-plugin-system-info#3]
in the docs.rs crate page it reports that there are some changesto tauri and some of your plugin functionality will be depreciated

can you update this plugin cause it seems really well made and I want to use it for my app!

![image](https://github.com/HuakunShen/tauri-plugin-system-info/assets/109196423/41157c3f-7d18-411a-8700-fb0dc46a7918)

thank you!

**Comment by HuakunShen** [comment]
Ok I will take a look. @zenitogr 
Can you provide the link to the page of this screenshot?

**Comment by HuakunShen** [comment]
I couldn't find the message you provide, but I upgraded Tauri to the latest version and also sysinfo crate. You can check the current version (v0.2.0) and see if there is any problem.

`sysinfo` crate had lots of API changes, I also made the changes accordingly.

Let me know and reopen if the message still exists. Closed for now.
